### ISSUE TITLE
web.config typo

### ISSUE THREAD

**Issue by JCFMachado** [arndta/TinyFileManager.NET#1]
Great work, thanks a lot for your effort!

I believe you have a typo in your web.config:

in the distro i downloaded you had  
...
applicationSettings
    TinyFileManager.Properties.Settings
....
and i had to change it to 
....
  applicationSettings
    TinyFileManager.NET.Properties.Settings
....
for it to work

Thanks again

**Comment by isaumya** [comment]
Good work. btw

**Comment by arndta** [comment]
Thanks for the help peoples.
