### ISSUE TITLE
Could not load type 'TinyFileManager.NET.dialog (2)

### ISSUE THREAD

**Issue by fabsvianna** [arndta/TinyFileManager.NET#11]
Hi,

I followed the instalation guide and when i tried to access de Dialog to test this error appears even recompiling in 64 bits.: 

Description: An error occurred during the parsing of a resource required to service this request. Please review the following specific parse error details and modify your source file appropriately. 

Parser Error Message: Could not load type 'TinyFileManager.NET.dialog'.

Source Error: 

Line 1:  <%@ Page Title="Tiny File Manager" Language="C#" AutoEventWireup="true" CodeBehind="dialog.aspx.cs" Inherits="TinyFileManager.NET.dialog" %>

My directory is:

C:\inetpub\wwwroot\tinyfilemanager.net

I copied the tinyfilemanager.net folder inside destro folder, inclunding all subfolders and files.

**Comment by arndta** [comment]
Two questions:
1. Do you have a public url to this page?
2. Did you create an application at C:\inetpub\wwwroot\tinyfilemanager.net?
