### ISSUE TITLE
Not working with latest version

### ISSUE THREAD

**Issue by maulinpandya2006** [arndta/TinyFileManager.NET#12]
Hello Sir can you please your TinyFileManager.NET 4.0 release is not working with Tinymce 4.1.2 latest release.
Please do the needful as soon as possible.

Thanks.

**Comment by arndta** [comment]
I have a bit more work to do, but you should be able to use the current plugin scripts that come in this repository with the new version.  It should work, from my testing.  The display is a little off with the button, but it works.

**Comment by maulinpandya2006** [comment]
Sir thanks for the reply.
I did same as you mentioned and everything is working but when i open the source code window and press ok to release the code, the popup window can not be close and remain open. Cancel button is working but Ok button dos not work.
any suggestion?

**Comment by arndta** [comment]
I really have no suggestion, I'm sorry.  The source code editor is not part
of the TinyFileManager customization at all.

Good luck

**Comment by maulinpandya2006** [comment]
Ohh thats ok. For your knowledge currently your demo is not working.  You
can check it.

Thanks.
