### ISSUE TITLE
Typo in clsConfig.cs?

### ISSUE THREAD

**Issue by averias** [arndta/TinyFileManager.NET#2]
Hi arndta, 

I think there is a typo en TinyFileManager.NET / classes / clsConfig.cs in line 150:

150: strRet += "," + clsConfig.strAllowedImageExtensions;

Shouldn't it be:

strRet += "," + clsConfig.strAllowedFileExtensions; ?

to add file extensions different to  image, music and video file extensions.

Great job arndta, very good plugin. Thank you very much

**Comment by arndta** [comment]
Pushed a commit to fix this, thanks for pointing it out!
