### ISSUE TITLE
Image Upload - Safari browser support

### ISSUE THREAD

**Issue by akshayesoft** [arndta/TinyFileManager.NET#4]
Hi,

I have customized the file structure to suit my needs. As a result, I had to publish it as a web application in the site rather than a virtual directory. All works well, except for image upload feature in safari. Safari does not support drag and drop. I select the required file to upload, and what next? I don't see an upload button. Is there a work around for this? 

Great piece of code. Wonderful interface by the way. Loved working on it. 

Thanks!

**Comment by arndta** [comment]
So when you say you select the file, are you referring to clicking on the dropzone and selecting from the file browser or are you getting the fallback standard file upload dialog?

You should be able to click on the dropzone and it will automatically start the upload, once you have selected the file(s).

**Comment by arndta** [comment]
Nevermind my last question, I see what you're referring to.

See the most recent commit for a fix to this.  Thanks for the heads up.
